[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#002060"
font = "sans serif"

// [server]
// port = 8501
// enableCORS = false

// [browser]
// serverPort = 8501
// serverAddress = "localhost"
// gatherUsageStats = false

// [runner]
// magicEnabled = true
// installTracer = false