name: underwriting_dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - openpyxl
  - xlrd
  - pyxlsb
  - sqlite
  - streamlit
  - plotly
  - dash
  - folium
  - pytest
  - jupyter
  - notebook
  - black
  - flake8